### ISSUE TITLE
Redactor Style Plugin not working in Craft CMS v.2.3.2640

### ISSUE THREAD

**Issue by brianrivet** [aelvan/RedactorStyles-Craft#3]
Hi,

I am running the Redactor Styles plugin on a craft site I am working on and I just updated Craft to v.2.3.2640. Since I did the update the redactor styles plugin no longer appears in my list of plugins installed on the site and any rich text fields that I had using Redactor styles are not rendering in the control panel. When I look at the javascript console I see an error in the control panel on pages with the redactor rich text fields that says "Uncaught ReferenceError: RedactorStyles is not defined"

**Comment by aelvan** [comment]
Which version of Craft did you upgrade from? The old version of Redactor Styles was for Redactor 9, which was used in Craft until version 2.3. So if you upgraded from 2.2 or earlier, you need to download the latest version of Redactor Styles and update it.

**Comment by brianrivet** [comment]
I updated from Craft v. 2.3.2636 to 2.3.2640. I was running v.0.3 of Redactor Styles.

**Comment by aelvan** [comment]
That is weird, I'm running it on two 2.3.2640 installs right now, and it works fine. Have you checked in the redactor styles settings (in the control panel) that the "Styles JSON Object" still has data? And is it valid javascript?

**Comment by brianrivet** [comment]
There isn't anything in the control panel for Redactor Styles. Its almost like the plugin uninstalled when the update ran. I am looking at ftp and there is a RedactorStyles folder in my plugins folder, but it's like it isn't being recognized by Craft.

**Comment by aelvan** [comment]
That is weird! Is the plugin folder still named "redactorstyles"? Try deleting the "redactorstyles" plugin folder, download the plugin from github, and replace it? No other errors in the console?

**Comment by brianrivet** [comment]
got it resolved. The name of the folder for the plugin was in camelcase and that was apparently causing the issue. When I changed the folder to all lower case it picked it up.

**Comment by aelvan** [comment]
Ah, yes that would be a problem, at least on some webservers/os'. Glad you got it solved, have a nice day! :)
