### ISSUE TITLE
Please add a license to this project!

### ISSUE THREAD

**Issue by adrienne** [aelvan/RedactorStyles-Craft#5]
Please add a license to this code so folks can feel safe using it in their projects? I recommend the BSD 3-Clause License, myself, but it genuinely doesn't matter so long as the code is licensed under SOME terms.

**Comment by aelvan** [comment]
I've added a license (MIT) to the repo.

**Comment by adrienne** [comment]
Thanks so much! <3 I just can't use code without SOME license, because it makes some clients (justifiably) really twitchy.
